---
substitutions:
  device_name: test_dimmer # hostname & entity_id
  friendly_name: Test Dimmer # Displayed in HA frontend
  pwm_min_power: 1% # keep dimming functional at lowest levels
  gamma_correct: "1.0"
  no_delay: 0s # transition when changing dimmer_lvl & relay delay
  transition_length: .5s # transition when turning on/off
  long_press_min: .4s # minimum time to activate long-press action
  long_press_max: 2s # maximum time to activate long-press action
  default_bri_up: 100% # default brightness for turn on by up button
  default_bri_down: 33% # default brightness for turn on by down button
  default_bri: 50% # default brightness for turn on by long press main button

esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
  on_boot:
    - lambda: |-
        id(virtual_dimmer).add_new_target_state_reached_callback([]() {
          auto offset = id(multiphase_dimmer_position) - 1;
          auto factor = id(multiphase_dimmer_phases);
          id(vdimmer_lvl) = id(virtual_dimmer).current_values.get_brightness();
          auto new_pdimmer_lvl = clamp(id(vdimmer_lvl) * factor - offset, 0, 1);
          id(pdimmer_lvl) = new_pdimmer_lvl;
          auto call = id(physical_dimmer).make_call();
          call.set_state(id(virtual_dimmer).current_values.get_state());
          call.set_brightness(new_pdimmer_lvl);
          call.set_transition_length(0);
          call.perform();
        });
  on_loop:
    - lambda: |-
        auto offset = id(multiphase_dimmer_position) - 1;
        auto factor = id(multiphase_dimmer_phases);
        auto new_pdimmer_lvl = clamp(id(vdimmer_lvl) * factor - offset, 0, 1);
        if (id(pdimmer_lvl) == new_pdimmer_lvl) return;
        id(pdimmer_lvl) = new_pdimmer_lvl;
        auto call = id(physical_dimmer).make_call();
        call.set_state(new_pdimmer_lvl > 0);
        call.set_brightness(new_pdimmer_lvl);
        call.set_publish(false);
        call.set_transition_length(0);
        call.perform();

wifi:
  ssid: "iot153"
  password: "mjunhybgt"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}_AP
    password: "CheZUQdIYjry"

web_server:
  port: 80

captive_portal:

logger:

# Enable Home Assistant API
api:

mqtt:
  id: mqtt_client
  broker: 192.168.8.6
  discovery: false

ota:

output:
  - id: led5
    pin: GPIO3
    platform: esp8266_pwm
    inverted: true

  - id: led4
    pin: GPIO5
    platform: esp8266_pwm
    inverted: true

  - id: led3
    pin: GPIO12
    platform: esp8266_pwm
    inverted: true

  - id: led2
    pin: GPIO14
    platform: esp8266_pwm
    inverted: true

  - id: phys_pwm
    pin: GPIO13
    platform: esp8266_pwm
    power_supply: relay
    min_power: ${pwm_min_power}

  - id: red_led
    pin: GPIO4
    platform: esp8266_pwm
    inverted: true

  - id: virtual_dimmer_output
    platform: template
    type: float
    write_action:
      - globals.set:
          id: vdimmer_lvl
          value: !lambda return state;
      - lambda: |-
          id(red_led).set_level(id(vdimmer_lvl) == 0.0f ? 0.5 : 0.0f);
          id(led2).set_level(id(vdimmer_lvl) * 5 - 1);
          id(led3).set_level(id(vdimmer_lvl) * 5 - 2);
          id(led4).set_level(id(vdimmer_lvl) * 5 - 3);
          id(led5).set_level(id(vdimmer_lvl) * 5 - 4);

status_led:
  pin:
    number: GPIO4
    inverted: true

light:
  - id: physical_dimmer
    platform: monochromatic
    name: Physical Dimmer
    output: phys_pwm
    gamma_correct: ${gamma_correct}
    default_transition_length: ${no_delay}
  - id: virtual_dimmer
    platform: monochromatic
    name: Virtual Dimmer
    output: virtual_dimmer_output
    gamma_correct: ${gamma_correct}
    default_transition_length: ${no_delay}

power_supply:
  - id: relay
    pin:
      number: GPIO16
      inverted: true
    enable_time: ${no_delay}
    keep_on_time: ${no_delay}

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
    name: ${friendly_name} Up Button
    mqtt_id: up_button_mqtt
    id: up_button
    internal: false
    on_press:
      then:
        - if:
            condition:
              light.is_on: virtual_dimmer
            then:
              - lambda: |-
                  auto bri = id(virtual_dimmer).current_values.get_brightness();
                  id(action_start_bri) = bri;
                  auto call = id(virtual_dimmer).turn_on();
                  call.set_brightness(1.0);
                  call.set_publish(false);
                  auto transition_length = (1.0 - bri) * id(full_dim_dur_ms);
                  call.set_transition_length(transition_length);
                  call.perform();
            else:
              - globals.set:
                  id: action_start_bri
                  value: "-1"
              - light.turn_on:
                  id: virtual_dimmer
                  brightness: ${default_bri_up}
                  transition_length: ${transition_length}
    on_release:
      then:
        - lambda: |-
            auto start_bri = id(action_start_bri);
            auto new_bri = id(virtual_dimmer).current_values.get_brightness();
            if (start_bri < 0) return;
            auto level_delta = std::abs(new_bri - start_bri);
            if (level_delta > 0 && level_delta < 0.1) {
              new_bri = start_bri + 0.1;
            }
            new_bri = esphome::clamp(new_bri, 0.01, 1.0f);
            auto call = id(virtual_dimmer).turn_on();
            call.set_brightness(new_bri);
            call.set_transition_length(0);
            call.perform();
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
      mode: INPUT_PULLUP
    name: ${friendly_name} Down Button
    id: down_button
    internal: false
    on_press:
      then:
        - if:
            condition:
              light.is_on: virtual_dimmer
            then:
              - lambda: |-
                  auto bri = id(virtual_dimmer).current_values.get_brightness();
                  id(action_start_bri) = bri;
                  auto call = id(virtual_dimmer).turn_on();
                  call.set_brightness(0.01);
                  call.set_publish(false);
                  auto transition_length = bri * id(full_dim_dur_ms);
                  call.set_transition_length(transition_length);
                  call.perform();
            else:
              - globals.set:
                  id: action_start_bri
                  value: "-1"
              - light.turn_on:
                  id: virtual_dimmer
                  brightness: ${default_bri_down}
                  transition_length: ${transition_length}

    on_release:
      then:
        - lambda: |-
            auto start_bri = id(action_start_bri);
            auto new_bri = id(virtual_dimmer).current_values.get_brightness();
            if (start_bri < 0) return;
            auto level_delta = std::abs(new_bri - start_bri);
            if (level_delta > 0 && level_delta < 0.1) {
              new_bri = start_bri - 0.1;
            }
            new_bri = esphome::clamp(new_bri, 0.01, 1.0f);
            auto call = id(virtual_dimmer).turn_on();
            call.set_brightness(new_bri);
            call.set_transition_length(0);
            call.perform();
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    name: ${friendly_name} Main Button
    mqtt_id: main_button_mqtt
    id: main_button
    internal: false
    on_press:
      then:
        - light.toggle:
            id: virtual_dimmer
    on_click:
      min_length: ${long_press_min}
      max_length: ${long_press_max}
      then:
        - globals.set:
            id: action_start_bri
            value: "-1"
        - light.turn_on:
            id: virtual_dimmer
            brightness: ${default_bri}
            transition_length: ${transition_length}

globals:
  - id: pdimmer_lvl
    type: float
    initial_value: "1.0"
  - id: vdimmer_lvl
    type: float
    initial_value: "1.0"
  - id: action_start_bri
    type: float
  - id: full_dim_dur_ms
    type: float
    initial_value: "3000"
    restore_value: true
  - id: multiphase_dimmer_phases
    type: uint8_t
    initial_value: "2"
    restore_value: true
  - id: multiphase_dimmer_position
    type: uint8_t
    initial_value: "2"
    restore_value: true
